version: '3.4'

services:
  ping:
    image: ${DOCKER_REGISTRY-}ping
    container_name: ping
    build:
      context: .
      dockerfile: Ping\Dockerfile

  pong:
    image: ${DOCKER_REGISTRY-}pong
    container_name: pong
    build:
      context: .
      dockerfile: Pong\Dockerfile

  winners:
    image: ${DOCKER_REGISTRY-}winners
    container_name: winners
    build:
      context: .
      dockerfile: WinnersWorker\Dockerfile

  rabbit-mq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes: 
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/lgb/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 15672:15672
      - 5672:5672

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/